id: P004430
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN5026
  title: ཕུག་ལུགས་རྩིས་ཀྱི་ལེགས་བཤད་བཻ་ཌཱུར་དཀར་པོ།
  author: ''
  volumes:
    efa6ce37614f438db68f86a8a75c6583:
      image_group_id: I3CN5028
      title: ''
      volume_number: 1
      total_pages: 468
      base_file: v001.txt
    0550dc789c9b486580a8e2b899fbd2fa:
      image_group_id: I3CN5029
      title: ''
      volume_number: 2
      total_pages: 554
      base_file: v002.txt
