id: I3864355D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T00:38:47+00:00'
last_modified: '2022-06-08T00:57:57.312730+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5026
  title: ཕུག་ལུགས་རྩིས་ཀྱི་ལེགས་བཤད་བཻ་ཌཱུར་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9E14:
      image_group_id: I3CN5028
      title: ''
      total_pages: 468
      order: 1
      base_file: 9E14.txt
    AF0F:
      image_group_id: I3CN5029
      title: ''
      total_pages: 554
      order: 2
      base_file: AF0F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
