id: I3864355D
legacy_id: P004430
ocr_import_info:
  bdrc_scan_id: W3CN5026
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T00:34:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:44:40.214647+00:00'
last_modified: 2022-09-03 22:45:51.710057
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5026
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5026
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕུག་ལུགས་རྩིས་ཀྱི་ལེགས་བཤད་བཻ་ཌཱུར་དཀར་པོ།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8859365367479723
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I3CN5029:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5029
      total_pages: 554
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN5029.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.874835959270377
    legacy_id: v002
  I3CN5028:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5028
      total_pages: 468
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5028.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8983468389109602
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
